using Windows.Win32.System.Memory;

namespace CoreHook.BinaryInjection.Memory;

public enum MemoryProtectionType : uint
{
    Execute = PAGE_PROTECTION_FLAGS.PAGE_EXECUTE,
    ExecuteRead = PAGE_PROTECTION_FLAGS.PAGE_EXECUTE_READ,
    ExecuteReadWrite = PAGE_PROTECTION_FLAGS.PAGE_EXECUTE_READWRITE,
    ExecuteWriteCopy = PAGE_PROTECTION_FLAGS.PAGE_EXECUTE_WRITECOPY,
    NoAccess = PAGE_PROTECTION_FLAGS.PAGE_NOACCESS,
    ReadOnly = PAGE_PROTECTION_FLAGS.PAGE_READONLY,
    ReadWrite = PAGE_PROTECTION_FLAGS.PAGE_READWRITE,
    WriteCopy = PAGE_PROTECTION_FLAGS.PAGE_WRITECOPY,
    GuardModifierflag = PAGE_PROTECTION_FLAGS.PAGE_GUARD,
    NoCacheModifierflag = PAGE_PROTECTION_FLAGS.PAGE_NOCACHE,
    WriteCombineModifierflag = PAGE_PROTECTION_FLAGS.PAGE_WRITECOMBINE
}
